### ISSUE TITLE
KDBX Database paths outside project directory give FileNotFoundException

### ISSUE THREAD

**Issue by andrewmurray** [adamfisher/KeePass.Extensions.Configuration#1]
I have configured the extension to pull the KDBX file from `C:\source\secrets\KeepassConfigTest.kdbx`.

The project lives in the directory `C:\Users\andrew.murray\source\repos\KeepassConfigTest\KeepassConfigTest`.

The following exception is thrown when the KDBX file lives outside the executing project's directory.
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not find file 'C:\Users\andrew.murray\source\repos\KeepassConfigTest\KeepassConfigTest\KeepassConfigTest.kdbx'.
  Source=System.Private.CoreLib
  StackTrace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at KeePassLib.Serialization.DefaultFilesProvider.OpenReadLocal(String fullname)
   at KeePassLib.Serialization.IOConnection.OpenReadLocal(IOConnectionInfo ioc)
   at KeePassLib.Serialization.IOConnection.OpenRead(IOConnectionInfo ioc)
   at KeePassLib.PwDatabase.Open(IOConnectionInfo ioSource, CompositeKey pwKey, IStatusLogger slLogger)
   at KeePass.Extensions.Configuration.KeePassConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at KeePass.Extensions.Configuration.KeePassConfigurationExtensions.AddKeePass(IConfigurationBuilder builder, String path, CompositeKey compositeKey, IOConnectionInfo connection, Func`2 filterEntries, Func`2 resolveKey, Func`3 resolveValue, IFileProvider provider, Boolean optional, Boolean reloadOnChange)
   at Program.<Main>$(String[] args) in C:\Users\andrew.murray\source\repos\KeepassConfigTest\KeepassConfigTest\Program.cs:line 10

  This exception was originally thrown at this call stack:
    Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(string, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
    Microsoft.Win32.SafeHandles.SafeFileHandle.Open(string, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions, long)
    System.IO.Strategies.OSFileStreamStrategy.OSFileStreamStrategy(string, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions, long)
    System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(string, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions, long)
    System.IO.Strategies.FileStreamHelpers.ChooseStrategy(System.IO.FileStream, string, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, int, System.IO.FileOptions, long)
    System.IO.FileStream.FileStream(string, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
    KeePassLib.Serialization.DefaultFilesProvider.OpenReadLocal(string)
    KeePassLib.Serialization.IOConnection.OpenReadLocal(KeePassLib.Serialization.IOConnectionInfo)
    KeePassLib.Serialization.IOConnection.OpenRead(KeePassLib.Serialization.IOConnectionInfo)
    KeePassLib.PwDatabase.Open(KeePassLib.Serialization.IOConnectionInfo, KeePassLib.Keys.CompositeKey, KeePassLib.Interfaces.IStatusLogger)
    ...
    [Call Stack Truncated]
```
![image](https://user-images.githubusercontent.com/557583/144820625-5aa882c9-5ead-4803-b0db-b827ca34b579.png)

Cloning the source and including as an existing project shows more detail:
![image](https://user-images.githubusercontent.com/557583/144820326-be09643c-f5b2-4038-97ae-e4f7bc70dbd6.png)

I believe this is due to the following line inside `KeePassConfigurationExtensions`:

```csharp
                path = Path.GetFileName(path);
```
Which strips the path up to the file name off the path which is then passed into the `IOConnectionInfo` constructor.

I have attached the following small reproduction: [KeepassConfigTest.zip](https://github.com/adamfisher/KeePass.Extensions.Configuration/files/7660819/KeepassConfigTest.zip)

I am happy to open a PR to remove the above line and I've ensured that the tests pass locally with it removed but I wanted to be sure this wasn't going to break any other use cases that I'm unaware of. @adamfisher could you comment on this please?

**Comment by adamfisher** [comment]
This should be fixed in version 1.2.
